[build-system]
requires = ["setuptools>=46.4.0", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "mypackage/version.py"
version_scheme = "release-branch-semver"

[tool.black]
line-length = 88
