name: Staging deployment

on:
  pull_request:
    types: [labeled]

env:
  PYTHON_VERSION: 3.8

jobs:
  docker-build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{github.repository}}/mypackage
          tag_with_ref: true
          add_git_labels: true
          cache_froms: python:${env:PYTHON_VERSION}-buster,python:${env:PYTHON_VERSION}-slim-buster,docker.pkg.github.com/jellevandehaterd/mypackage/mypackage
          build_args: PYTHON_VERSION=${env:PYTHON_VERSION}

  deploy:
    name: Deploy Docker image
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Dummy action
        run: docker ps -a
