name: Staging deployment

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: 3.8

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{github.repository}}/mypackage
          tag_with_ref: true
          add_git_labels: true
          cache_froms: python:${{ env.PYTHON_VERSION }}-buster,python:${{ env.PYTHON_VERSION }}-slim-buster,docker.pkg.github.com/jellevandehaterd/mypackage/mypackage:latest
          build_args: PYTHON_VERSION=${{ env.PYTHON_VERSION }}
